### ISSUE TITLE
Add type support via py.typed marker file for PEP561

### ISSUE THREAD

**Issue by jogo-openai** [Kludex/python-multipart#147]
As per [PEP561](https://peps.python.org/pep-0561/#packaging-type-information) mypy requires a py.typed file to consider a library typed. https://mypy.readthedocs.io/en/latest/installed_packages.html#creating-pep-561-compatible-packages.

Adding this file will allow folks to take advantage of the typing already present in this module.

Otherwise mypy reports:

> Skipping analyzing "multipart.multipart": module is installed, but missing library stubs or py.typed marker  [import-untyped]

**Comment by Kludex** [comment]
It's a warning that makes sense, since it's untyped...
