### ISSUE TITLE
Namespace conflict with `multipart` package

### ISSUE THREAD

**Issue by DManowitz** [Kludex/python-multipart#149]
It is not possible to install and use both this package and the [`multipart`](https://pypi.org/project/multipart/) package simultaneously.  Are these packages both trying to do the same thing?

**Comment by musicinmybrain** [comment]
In a previous issue, @Kludex wrote:

> I'm not fixing this.
> 
> My intention is to maintain this package till we merge the code to Starlette.

https://github.com/Kludex/python-multipart/issues/16
