### ISSUE TITLE
Rootless docker images get `permission denied`

### ISSUE THREAD

**Issue by smivv** [Kludex/python-multipart#181]
Hi,

I am having an issue with the code in your library:

```
/usr/local/lib/python3.11/dist-packages/starlette/formparsers.py:10: in <module>
    import multipart
/usr/local/lib/python3.11/dist-packages/multipart/__init__.py:10: in <module>
    if file_path.is_file():
/usr/lib/python3.11/pathlib.py:1267: in is_file
    return S_ISREG(self.stat().st_mode)
/usr/lib/python3.11/pathlib.py:1013: in stat
    return os.stat(self, follow_symlinks=follow_symlinks)
E   PermissionError: [Errno 13] Permission denied: '/root/multipart.py'
```

Please add handling of this issue!

**Comment by defnull** [comment]
If you do not want to wait for the PR to be merged, you could also update Starlette to the most recent release or pin `python-multipart` to version `0.0.12`. The fallback code that fails here is only invoked if you use a recent version of python-multipart together with an old version of Starlette or FastAPI.

**Comment by smivv** [comment]
Thanks, already did that. I will remove that once your fix is ready and released.
