### ISSUE TITLE
Incorrectly warns `Skipping data after the last boundary`

### ISSUE THREAD

**Issue by BiDuang** [Kludex/python-multipart#192]
Latest version (0.0.18) causes the `multipart` to incorrectly warn `Skipping data after last boundary` in every multipart request, even when the client sends the correct request format.

Downgrade library can slove this issue.

**Comment by Kludex** [comment]
Can you show me the request?

> Downgrade library can slove this issue.

I issued a security advisory, so I don't recommend that.

**Comment by Kludex** [comment]
Maybe it's because of two `\r\n` characters that are at the end?

**Comment by BiDuang** [comment]
> Can you show me the request?
> 
> > Downgrade library can slove this issue.
> 
> I issued a security advisory, so I don't recommend that.

Well, now every `multipart` request triggers this warning, for example:
```bash
curl --location --request POST 'http://localhost:8123/shop/add' \
--header 'User-Agent: Apifox/1.0.0 (https://apifox.com)' \
--header 'Authorization: Bearer undefined' \
--header 'Accept: */*' \
--header 'Host: localhost:8123' \
--header 'Connection: keep-alive' \
--header 'Content-Type: multipart/form-data; boundary=--------------------------939992003815200322287943' \
--form 'body="{  \"name\": \"foo\",  \"price\": 100.5,  \"description\": \"bar\"}"' \
--form 'img=@"someimg.png"'
```

**Comment by BiDuang** [comment]
> Maybe it's because of two `\r\n` characters that are at the end?

Oh, I think that might be the issue. I set a breakpoint and removed the `\r\n` from the boundary, and the warning is gone now.

**Comment by Kludex** [comment]
Let me try to fix it real quick.

**Comment by Kludex** [comment]
@BiDuang can you check https://github.com/Kludex/python-multipart/pull/193, please?

**Comment by BiDuang** [comment]
> @BiDuang can you check #193, please?

Ok, it works.

**Comment by Kludex** [comment]
Thanks. Released.
