### ISSUE TITLE
Integration with google oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by manunio** [Kludex/python-multipart#48]
Hi, I would like to help integrate this project into [OSS-Fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/8398, it contains necessary logic from an OSS-Fuzz perspective to integrate python-multipart, This includes developing initial fuzzers as well as integrating into OSS-Fuzz.

- Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects.

- If you would like to integrate, could I please have an email(s), it must be associated with a google account like gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

-  As an alternative, if you don't have a gmail id or you don't wish to provide your email, but still wish to integrate. I can add my mail id for time being and monitor bug/crashes.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by Kludex** [comment]
You still interested in helping me here? If yes, I'll provide the email.

I agree with the OSS-Fuzz thing here.

**Comment by Kludex** [comment]
Is this done?
