### ISSUE TITLE
Do not select a file, submit it directly, and report a strange error:multipart.multipart:Did not find CR at end of boundary

### ISSUE THREAD

**Issue by goophps** [Kludex/python-multipart#65]
errors：
multipart.multipart:Did not find CR at end of boundary

{
  "detail": "There was an error parsing the body"
}

my code:
@app.post("/chatbot/sources_files")
async def sources_files(files: list[UploadFile] = File(description='文件')):
    return 'a'

my env: 

python：3.10
fastapi：0.98.0

**Comment by Kludex** [comment]
Do you have an MRE?
