### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'encode'

### ISSUE THREAD

**Issue by lorenpike** [Kludex/python-multipart#78]
I get an error when sending a request from a C# client library stemming from the `parse_options_header`. This error only started cropping up in 0.0.7 and did not exist beforehand.

Here's some sample code to reproduce the error

With python-multipart==0.0.7:

```python
from multipart.multipart import parse_options_header

ctype, options = parse_options_header(
    b'form-data; name=parameters; filename="C:\Users\name\path\to\file.png";'
    b" filename*=utf-8''C%3A%5CUsers%5Cname%5Cpath%5Cto3%5Cfile.png"
)

print(ctype, options)
``` 

Output:

```
Traceback (most recent call last):
  File ".\bug.py", line 3, in <module>
    parse_options_header(
  File "M:\Metrized\in-progress\metrized-cv\venv\lib\site-packages\multipart\multipart.py", line 118, in parse_options_header
    options[key.encode('latin-1')] = value.encode('latin-1')
AttributeError: 'tuple' object has no attribute 'encode'
```

With python-multipart==0.0.6, the output is:

```
b'form-data' {b'name': b'parameters', b'filename': b'path\to\x0cile.png', b'filename*': b"utf-8''C%3A%5CUsers%5Cname%5Cpath%5Cto3%5Cfile.png"}
```

I believe a fix in `parse_options_header` could be (`multpart.py:111-112`):

```python
    for param in params:
        key, value = param
        if isinstance(value, tuple):          <---- These lines
            value = value[-1]                   <----
```

**Comment by jbvirt** [comment]
Assuming this is a `python-multipart` issue, there should also probably be a unit test written to cover this edge case.

**Comment by RobbeSneyders** [comment]
We're having the same error with [connexion](https://github.com/spec-first/connexion). Seems to be introduced by [this change](https://github.com/andrew-d/python-multipart/pull/75).

**Comment by lorenpike** [comment]
To catch anyone up to speed on the issue, this is related to MIME parameters and how they get parsed using the `email.message` module in Python. When the parameter is specified to include a character set and language information like in the example below:

 >  Content-Type: application/x-stuff; title*=us-ascii'en-us'This%20is%20%2A%2A%2Afun%2A%2A%2A 

[reference](https://datatracker.ietf.org/doc/html/rfc2231)

Python's `email.message.Message.get_param`  returns a 3-`tuple` **(CHARSET, LANGUAGE, VALUE)** [reference](https://docs.python.org/3/library/email.compat32-message.html#email.message.Message.get_param) instead of a `str`. This case wasn't accounted for when the code was refactored in the latest update. 

Here's a potential fix: #79

**Comment by h0rn3t** [comment]
+

**Comment by olehliubchyk** [comment]
+

**Comment by Kludex** [comment]
- Closed by https://github.com/Kludex/python-multipart/pull/79
